### ISSUE TITLE
Can deploy be automated via GitHub actions?

### ISSUE THREAD

**Issue by SarahU** [Tech-Risers-Women/Tech-Risers-Women.github.io#16]
Currently deploy is manually run. Possible to automate?

**Comment by gros-pataplouf** [comment]
Hi, after some error and trial with [this](https://fullstackopen.com/en/part11/getting_started_with_git_hub_actions) as a learning ressource, this [minimal pipeline](https://github.com/gros-pataplouf/Tech-Risers-Women.github.io/blob/test/deploy/.github/workflows/pipeline.yml)
 appears to work 
Which would be the steps of the pipeline  - testing, linting (currently commented out), deploying ? Would you like to have [only one prod, or more environments](https://dev.to/mktcode/multiple-environments-with-github-pages-53me )?

**Comment by gros-pataplouf** [comment]
Deploy to gh pages has been automated.
